export const chrome = {
  appName: 'Padel Mate',
  homeAria: 'Padel Mate home',
  footerAria: 'Padel Mate',
  wordmarkPadel: 'Padel',
  wordmarkMate: 'Mate',
  mainNavAria: 'Main navigation',
  groups: 'Groups',
  mates: 'Mates',
  openMenuAria: 'Open menu',
  manageAccounts: 'Manage accounts',
  leaveActivity: 'Leave activity',
  signOut: 'Sign out',
  dismissMessageAria: 'Dismiss message',
  loading: 'Loading your courts...',
  closeAria: 'Close',
  cancel: 'Cancel',
  refresh: 'Refresh',
  copied: 'Copied',
  copyInvite: 'Copy invite',
  whatsapp: 'WhatsApp',
  you: 'You',
  playerFallback: 'Player',
  goHome: 'Go to Padel Mate',
};
