export const dashboard = {
  hintAria: 'How leaderboard scoring works',
  hintTitle: 'How leaderboard scoring works',
  hintLive: 'Points are added only after a set is confirmed. Live scoring does not change this table.',
  hintWin: 'Winning players receive 10 points plus the game difference. Losing players receive 0.',
  hintEarly: 'A set ended early still counts as a win, with half the 10-point bonus plus the same difference.',
  hintExamples: `6-3 → 13 points each
7-6 → 11 points each
4-2 early → 7 points each`,
  hintGuests: 'Guests never rank. A registered player whose partner is a guest still earns full points.',
  columnWl: 'W-L',
  columnWlHint: 'Sets won and lost',
  columnDiff: 'Diff',
  columnDiffHint: 'Game differential',
  columnPoints: 'Points',
  columnPointsHint: 'Running total',
  hintRank: 'Rank is by points, then sets won, then differential, then games won, then name.',
  eyebrow: 'Scoring context',
  newActivity: 'New activity',
  historyOnly: 'This group is history only. A former mate must be invited again before new scores can start.',
  leaderboardTitle: 'Group leaderboard',
  setsSuffix: 'sets',
  rankHeader: '#',
  playerHeader: 'Player',
  gamesRecord: (won: number, lost: number) => `${won}-${lost} games`,
  playersTitle: 'Players',
  liveActivity: 'Live activity',
  ownerActivity: (name: string) => `${name}'s activity`,
  resumeScoring: 'Resume scoring',
  join: 'Join',
  rejoin: 'Rejoin',
  recentSetLog: 'Recent set log',
  lastFive: 'Last 5 activities',
  emptyLogs: 'Completed sets will appear here.',
  activityNumber: (number: number) => `Activity #${number}`,
  setSingular: 'set',
  setPlural: 'sets',
  vs: 'vs',
  conclusionPartial: 'Partial',
  conclusionDisregarded: 'Disregarded',
  conclusionAbandoned: 'Abandoned',
  conclusionFinal: 'Final',
  setPrefix: (setNumber: number) => `S${setNumber}`,
};
