export const errors = {
  signInToContinue: 'Sign in to continue.',
  accountSuspendedApi: 'Your account is suspended. Contact the administrator.',
  administratorRequired: 'Administrator access required.',
  unknownRequest: 'Unknown request.',
  missingParam: (name: string) => `Missing ${name}.`,
  saveFailed: 'Something went wrong while saving. Please try again.',
  generic: 'Something went wrong.',
  requestFailed: 'Request failed.',
  inviteCouldNotUpdate: 'That invite could not be updated.',
  inviteOpenFailed: 'Something went wrong opening this invite.',
  fillAllSlots: 'Fill all four match slots.',
  chooseTwoRegistered: 'Choose at least two registered players.',
  playersNoLongerExist: 'One or more selected players no longer exist.',
  mustBeInMatch: 'You must be one of the players in the match.',
  onlyScoreWithMates: 'You can only score matches with your mates.',
  needToBeMates: (first: string, second: string) => (
    `${first} and ${second} need to be mates with each other before you can open this group.`
  ),
  couldNotNumberActivity: 'Could not number this activity. Try starting the set again.',
  groupNotFound: 'Scoring group not found.',
  groupNotAvailable: 'This scoring group is not available.',
  activityNotFound: 'Activity session not found.',
  onlyGroupCanAccept: 'Only players in this scoring group can accept this activity.',
  deviceNotConnected: 'This device is not connected to the activity.',
  activityNotActive: 'This activity is not active.',
  waitForAccepts: 'Wait until every player in this group has accepted this activity.',
  activityPausedUntilRejoin: (names: string) => (
    `This activity is paused until ${names} rejoin.`
  ),
  onlyOwnerCanManageActivity: 'Only the activity owner can do that.',
  onlyControllersCanScore: 'Only the selected live-score devices can update the score.',
  chooseOneOrTwoControllers: 'Choose 1 or 2 players who have accepted this activity.',
  cannotAssignPendingController: 'A player must accept this activity before they can control the live score.',
  guestsCannotControlScore: 'Guests cannot control the live score.',
  finishSetBeforeTeams: 'Finish the current set before changing teams.',
  chooseExactlyTwoBlue: 'Choose exactly two players for Blue Team.',
  invalidScoreUpdate: 'Invalid score update.',
  startSetBeforeScoring: 'Start a set before scoring.',
  scoreUpdateUnavailable: 'Score update is unavailable.',
  scoreChangedTryPointAgain: 'The score changed on the other device. Please try that point again.',
  noActiveGame: 'There is no active game.',
  noGameResultToCancel: 'There is no game result to cancel.',
  nothingToUndo: 'Nothing to undo.',
  scoreChangedTryAgain: 'The score changed on the other device. Please try again.',
  noGameResultToConfirm: 'There is no game result to confirm.',
  noSetResultToCancel: 'There is no set result to cancel.',
  noSetResultToConfirm: 'There is no set result to confirm.',
  noActiveSet: 'There is no active set.',
  tiedPartialCannotCalculate: 'A tied partial set cannot be calculated. Continue playing or disregard it.',
  chooseHowToConclude: 'Choose how to conclude this set.',
  concludeBeforeFinishing: 'Conclude or disregard the current set before finishing.',
  deviceNoLongerConnected: 'This device is no longer connected. Rejoin the activity to continue.',
  deviceNeedsIdentity: 'This device needs a valid session identity.',
  inviteNotValid: 'That invite link is not valid.',
  inviteAlreadyUsed: 'That invite link has already been used.',
  inviteExpired: 'That invite link has expired. Ask for a new one.',
  cannotInviteSelf: 'You cannot invite yourself.',
  inviterGone: 'The player who sent this invite no longer exists.',
  inviteAlreadyUsedOrUnavailable: 'That invite link has already been used or is no longer available.',
  chooseMateToRemove: 'Choose a mate to remove.',
  notOneOfYourMates: 'That player is not one of your mates.',
  scoringUnavailable: 'Scoring is unavailable until the current step is resolved.',
  noScoreChangeToUndo: 'There is no score change to undo.',
  notices: {
    activityFinished: 'This activity has already finished.',
    inviteReplaced: 'New invite link ready. The previous link no longer works.',
    inviteReady: 'Invite link ready. Share it directly with the person you want to play with.',
    inviteDeleted: 'Invite link deleted.',
    mateRemoved: 'Mate removed.',
    reviewPartial: 'Review the saved partial set before continuing.',
    activityFinishedSaved: 'Activity finished and saved.',
    leftActivity: 'You left the activity. Rejoin from this group when you are ready.',
    ownerClosedActivity: 'The owner closed this activity.',
    youClosedActivity: 'You closed this activity.',
    joinedAnotherActivity: 'You can only be in one activity at a time.',
    leaveBeforeSwitching: 'Leave or finish the live activity before switching sections.',
    activityUpdated: 'Activity updated.',
  },
};
