export const invite = {
  nowMatesTitle: 'You are now mates',
  nowMatesBody: (inviterName: string) => `You and ${inviterName} can now score matches together.`,
  goToMates: 'Go to your mates',
  declinedTitle: 'Invite declined',
  declinedBody: (inviterName: string) => `You did not become mates with ${inviterName}. This link cannot be used again.`,
  invitedYou: (inviterName: string) => `${inviterName} invited you`,
  acceptBody: 'Accept to become mates and score matches together. You can decline if you do not want this connection.',
  accept: 'Accept invite',
  decline: 'Decline',
  notAvailable: 'Invite not available',
  shareTitle: 'Invite a mate',
  shareDescription: 'Share this single-use link. There is no directory to search.',
  shareValueLabel: 'Invite link',
  whatsappMessage: (url: string) => `Join me on Padel Mate: ${url}`,
  replaceTitle: 'Replace this invite link?',
  replaceDescription: 'Creating a new link deletes the current one. Anyone with the old link will not be able to use it.',
  createNewInvite: 'Create new invite',
};
