export const live = {
  activityUntitled: 'Activity',
  activityTitle: (number: number) => `Activity #${number}`,
  guestName: (n: number) => `Guest ${n}`,
  blueTeam: 'Blue Team',
  redTeam: 'Red Team',
  vs: 'VS',
  chooseTwoPlayers: 'Choose 2 players',
  waiting: 'Waiting',
  share: 'Share',
  setTeamsHeading: (setNumber: number) => `Set ${setNumber} teams`,
  setTeamsIntro: 'Pick two slots for Blue Team. The other two play for Red Team. Guests play but do not rank.',
  whoIsIn: 'Who is in this activity',
  everyoneIn: 'Everyone is in',
  inCount: (inCount: number, total: number) => `${inCount}/${total} in`,
  accepted: 'Accepted this activity',
  notOpened: 'Has not opened the code or link yet',
  in: 'In',
  pending: 'Pending',
  shareSoTheyAccept: 'Share the code or link so they can accept.',
  leftWaitingToRejoin: 'Left. Waiting for them to rejoin.',
  scoreControllers: 'Live score devices',
  scoreControllersHint: 'Choose 1 or 2 players who have accepted. Their phones show the live red and blue scoreboard.',
  scoreControllerSlot: (selected: number) => `${selected}/2`,
  watchingHint: 'You are watching. You cannot update the score.',
  waitingForOwnerToConfirmGame: (ownerName: string) => `Waiting for ${ownerName} to confirm this game.`,
  waitingForOwnerToConfirmSet: (ownerName: string) => `Waiting for ${ownerName} to confirm this set.`,
  waitingForNextSet: (ownerName: string) => `Waiting for ${ownerName} to start the next set.`,
  pausedWaiting: (names: string) => `Paused until ${names} rejoin.`,
  ownerOnlyTeams: 'Only the activity owner can pick teams and start a set.',
  blueTeamPlayers: 'Blue Team players',
  blueSelected: (selected: number) => `${selected}/2 selected`,
  thisActivity: 'This activity',
  completedCount: (count: number) => `${count} completed`,
  noCompletedSets: 'No completed sets yet.',
  finishActivity: 'Finish activity',
  startSet: (setNumber: number) => `Start set ${setNumber}`,
  setNumber: (setNumber: number) => `Set ${setNumber}`,
  controllerCap: (count: number) => `${count}/2 scoring`,
  scoreHistory: 'Score history',
  shareActivity: 'Share activity',
  leaveActivity: 'Leave activity',
  scoreboardAria: 'Live Padel scoreboard',
  pointToBlueAria: (names: string) => `Point to Blue Team, ${names}`,
  pointToRedAria: (names: string) => `Point to Red Team, ${names}`,
  setGamesAria: (blue: number, red: number) => `Set games, Blue ${blue}, Red ${red}`,
  games: 'Games',
  point: 'Point',
  undo: 'Undo',
  endSet: 'End set',
  offline: 'Offline',
  retrying: 'Retrying',
  saving: 'Saving',
  saved: 'Saved',
  cancelResult: 'Cancel result',
  gameWon: (team: string) => `${team} won this game`,
  updateSetScorePrompt: 'Update the set score and begin a fresh game?',
  updateSetScore: 'Update set score',
  setWon: (team: string) => `${team} won the set`,
  setWonDescription: (blue: number, red: number) => (
    `Final set score: ${blue}-${red}. Confirm to update this group's leaderboard.`
  ),
  updateLeaderboard: 'Update leaderboard',
  shareTitle: 'Invite players to this activity',
  shareDescription: 'Share the code or link so every registered member can accept.',
  sessionCode: 'Session code',
  whatsappMessage: (title: string, url: string) => `Join Padel Mate ${title}. ${url}`,
  endSetEarly: 'End this set early?',
  partialSetScore: (blue: number, red: number) => `The current set score is Blue ${blue}, Red ${red}.`,
  tiedPartialWarning: 'A tied partial set cannot be calculated. Continue playing or disregard it.',
  calculatePartial: 'Calculate partial result',
  disregardSet: 'Disregard this set',
  continuePlaying: 'Continue playing',
  historyEyebrow: 'Current game only',
  closeHistoryAria: 'Close history',
  noScoreChanges: 'No score changes in this game yet.',
  undidLastPoint: 'Undid the last point',
  canceledGameResult: 'Canceled game result',
  pointToTeam: (team: string) => `Point to ${team}`,
};
